name: Build on arm64 and publish docker image to DockerHub

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: uraimo/run-on-arch-action@v2
      name: Build artifact
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu18.04
        githubToken: ${{ github.token }}
        run: |
          uname -a
          echo "Build and test with Gradle"
          cp -f Dockerfile.gradle.arm64 Dockerfile.gradle && ./gradlew buildDocker -Dorg.gradle.jvmargs="-Xms512M -Xmx4G" -Dorg.gradle.daemon=false
          echo "Log into Docker Hub registry"
          echo "${{ secrets.DHUB_TOKEN }}" | docker login -u rossonet --password-stdin
          echo "Push image on Docker Hub"
          docker push rossonet/ar4k-bee:latest
    - name: Print env
      run: echo $GITHUB_ACTOR && uname -a
